-- 1. activity_logs table
-- 2. helper functions
-- 3. HR audit trigger function
-- 4. table triggers

create table if not exists public.activity_logs (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  actor_user_id text,
  actor_role varchar(20),
  entity_type varchar(30) not null,
  entity_id text not null,
  action_type varchar(30) not null,
  summary text not null,
  metadata jsonb not null default '{}'::jsonb
);

create index if not exists idx_activity_logs_created_at on public.activity_logs (created_at desc);
create index if not exists idx_activity_logs_entity_type on public.activity_logs (entity_type);
create index if not exists idx_activity_logs_action_type on public.activity_logs (action_type);
create index if not exists idx_activity_logs_actor_user_id on public.activity_logs (actor_user_id);

alter table public.activity_logs enable row level security;

drop policy if exists activity_logs_admin_select_policy on public.activity_logs;

create policy activity_logs_admin_select_policy
on public.activity_logs
for select
using (
  exists (
    select 1
    from public."user" u
    where u.userid = (select auth.uid())::text
      and u.user_type in ('ADMIN', 'SUPERADMIN')
      and u.record_status = 'ACTIVE'
  )
);

create or replace function private.current_actor_role()
returns varchar
language sql
security definer
set search_path to ''
as $$
  select coalesce((
    select u.user_type
    from public."user" u
    where u.userid = (select auth.uid())::text
    limit 1
  ), 'SYSTEM')::varchar;
$$;

revoke all on function private.current_actor_role() from public, anon, authenticated;

create or replace function private.insert_activity_log(
  entity_type_value varchar,
  entity_id_value text,
  action_type_value varchar,
  summary_value text,
  metadata_value jsonb default '{}'::jsonb
)
returns void
language plpgsql
security definer
set search_path to ''
as $$
begin
  insert into public.activity_logs (
    actor_user_id,
    actor_role,
    entity_type,
    entity_id,
    action_type,
    summary,
    metadata
  )
  values (
    (select auth.uid())::text,
    private.current_actor_role(),
    entity_type_value,
    entity_id_value,
    action_type_value,
    summary_value,
    coalesce(metadata_value, '{}'::jsonb)
  );
end;
$$;

revoke all on function private.insert_activity_log(varchar, text, varchar, text, jsonb) from public, anon, authenticated;

create or replace function public.log_hr_activity()
returns trigger
language plpgsql
security definer
set search_path to ''
as $$
declare
  entity_type_value varchar(30);
  entity_id_value text;
  action_value varchar(30);
  stamp_value text;
  old_status_value text;
  new_status_value text;
begin
  stamp_value := to_char(now(), 'YYYY-MM-DD HH24:MI:SS');
  old_status_value := case when TG_OP = 'INSERT' then null else OLD.record_status end;
  new_status_value := NEW.record_status;
  entity_type_value := case TG_TABLE_NAME
    when 'employee' then 'EMPLOYEE'
    when 'job' then 'JOB'
    when 'department' then 'DEPARTMENT'
    when 'jobhistory' then 'JOB_HISTORY'
    else upper(TG_TABLE_NAME)
  end;

  if TG_TABLE_NAME = 'employee' then
    entity_id_value := coalesce(NEW.empno, OLD.empno)::text;
  elsif TG_TABLE_NAME = 'job' then
    entity_id_value := coalesce(NEW.jobcode, OLD.jobcode)::text;
  elsif TG_TABLE_NAME = 'department' then
    entity_id_value := coalesce(NEW.deptcode, OLD.deptcode)::text;
  elsif TG_TABLE_NAME = 'jobhistory' then
    entity_id_value := concat_ws(':', coalesce(NEW.empno, OLD.empno), coalesce(NEW.jobcode, OLD.jobcode), coalesce(NEW.effdate, OLD.effdate));
  else
    entity_id_value := 'UNKNOWN';
  end if;

  if TG_OP = 'INSERT' then
    action_value := 'ADD';
  elsif coalesce(old_status_value, 'ACTIVE') <> 'INACTIVE' and new_status_value = 'INACTIVE' then
    action_value := 'DEACTIVATE';
  elsif old_status_value = 'INACTIVE' and new_status_value = 'ACTIVE' then
    action_value := 'RECOVER';
  else
    action_value := 'EDIT';
  end if;

  NEW.stamp := stamp_value;

  perform private.insert_activity_log(
    entity_type_value,
    entity_id_value,
    action_value,
    entity_type_value || ' ' || action_value || ' ' || entity_id_value,
    jsonb_build_object(
      'table', TG_TABLE_NAME,
      'old_record_status', old_status_value,
      'new_record_status', new_status_value
    )
  );

  return NEW;
end;
$$;

drop trigger if exists employee_audit_trigger on public.employee;
drop trigger if exists job_audit_trigger on public.job;
drop trigger if exists department_audit_trigger on public.department;
drop trigger if exists jobhistory_audit_trigger on public.jobhistory;

create trigger employee_audit_trigger
before insert or update on public.employee
for each row execute function public.log_hr_activity();

create trigger job_audit_trigger
before insert or update on public.job
for each row execute function public.log_hr_activity();

create trigger department_audit_trigger
before insert or update on public.department
for each row execute function public.log_hr_activity();

create trigger jobhistory_audit_trigger
before insert or update on public.jobhistory
for each row execute function public.log_hr_activity();
